-- Tabel voor potje afrekeningen
CREATE TABLE IF NOT EXISTS potje_afrekeningen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambassadeur_naam TEXT NOT NULL,
    straat TEXT NOT NULL,
    telefoon TEXT NOT NULL,
    email TEXT,
    bonregels JSONB,
    totaal_bedrag NUMERIC(10,2),
    bonnetjes_urls JSONB,
    vervolg TEXT CHECK (vervolg IN ('nieuw_potje', 'stoppen')),
    status TEXT DEFAULT 'nieuw' CHECK (status IN ('nieuw', 'in_behandeling', 'afgehandeld')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS inschakelen
ALTER TABLE potje_afrekeningen ENABLE ROW LEVEL SECURITY;

-- Anon kan inserten (formulier)
CREATE POLICY "Anon kan afrekeningen inserten"
    ON potje_afrekeningen FOR INSERT
    TO anon
    WITH CHECK (true);

-- Anon kan NIET lezen/updaten/deleten
-- (Alleen via service_role / dashboard)
